FROM dcycle/drupal:9php8

# Download contrib modules
# stage_file_proxy: During local development, fetch files from the stage site
# if they do not.
# smtp: Mail should be sent to a dummy mail interface, see ./README.md for
# details.
# See https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors
RUN export COMPOSER_MEMORY_LIMIT=-1 && composer require \
  drupal/devel \
  drupal/field_group \
  drupal/token \
  drupal/metatag \
  drupal/pathauto \
  drupal/webform:^6 \
  drupal/paragraphs \
  drupal/masquerade \
  drupal/bootstrap \
  drupal/stage_file_proxy \
  drupal/smtp

# Example of how to apply a patch.
# RUN curl -O https://www.drupal.org/files/issues/2752961-114.patch
# RUN patch -p1 < 2752961-114.patch
# RUN rm 2752961-114.patch

# Add some files to our container. See each individual file for details.
ADD drupal/settings/settings.php /var/www/html/sites/default/settings.php
ADD drupal/settings/services.yml /var/www/html/sites/default/services.yml

# Avoid memory limits with large database imports.
RUN echo 'memory_limit = 512M' >> /usr/local/etc/php/php.ini

RUN apt-get update && \
  apt-get --no-install-recommends -y install rsyslog && \
  rm -rf /var/lib/apt/lists/* && \
  echo 'local0.* /var/log/drupal.log' >> /etc/rsyslog.conf

# Avoid memory limits with large database imports.
RUN echo 'upload_max_filesize = 25M' >> /usr/local/etc/php/php.ini
RUN echo 'post_max_size = 25M' >> /usr/local/etc/php/php.ini

COPY drupal/scripts /scripts

COPY drupal/custom-modules /var/www/html/modules/custom
COPY drupal/custom-themes /var/www/html/themes/custom
COPY drupal/config /var/www/config
COPY drupal/starter-data /starter-data
