---
version: '3'

services:
  # We are splitting Apache and Drupal, see
  # https://blog.dcycle.com/blog/2022-03-25/php-apache-different-containers/
  webserver:
    build:
      context: .
      dockerfile: Dockerfile-nginx-only
    volumes:
      - "./do-not-commit:/do-not-commit:rw"
      - "drupal-files:/var/www/html/sites/default/files:rw"
    ports:
      - "80"

  # We are splitting Apache and Drupal, see
  # https://blog.dcycle.com/blog/2022-03-25/php-apache-different-containers/
  drupal:
    build:
      context: .
      dockerfile: Dockerfile-drupal-dev
    environment:
      # The virtual host is used when we want to access our site via an
      # Nginx Proxy locally; and is required by the script
      # ./scripts/https-deploy.sh.
      # See https://blog.dcycle.com/blog/2018-10-27 for details.
      # See also https://blog.dcycle.com/blog/7f3ea9e1/
      # See also https://blog.dcycle.com/blog/170a6078/
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL="letsencrypt@${VIRTUAL_HOST}"
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - HASH_SALT=${HASH_SALT}
    volumes:
      - "./do-not-commit:/do-not-commit:rw"
      - "drupal-files:/var/www/html/sites/default/files:rw"
      - "drupal-private-files:/drupal-private-files:rw"
      - "./drupal/settings/local-settings:/local-settings"
    links:
      - mysql:mysql
    working_dir: /var/www/html

  # Database server
  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - "mysql:/var/lib/mysql"

# Specifying the network name makes it predictable on all environments,
# for example when running ./scripts/migrate-all.sh, or when running browser
# tests on a CI environment, or any other tasks which requires external
# docker containers to connect to our network.
# This network (starterkit_drupal8site_default) has been previously created in
# ./scripts/deploy.sh
# See https://github.com/docker/compose/issues/3736.
networks:
  default:
    external:
      name: starterkit_drupal8site_default

volumes:
  mysql:
  drupal-files:
  drupal-private-files:
