# https://blog.dcycle.com/blog/2022-03-25/php-apache-different-containers/
FROM nginx:alpine

COPY docker-resources/nginx-webgrind/default.conf /etc/nginx/conf.d/
COPY --from=dcycle/webgrind:1 /var/www/html /var/www/html
