schemas:
  bootstrap: 8000
  my_custom_theme: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: /themes/contrib/bootstrap/favicon.ico
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
